name: empire_sim
description: A generational society and empire simulation.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0 # Required for the currency formatting in the code

flutter:
  uses-material-design: true